//
// Created by hw730 on 2020/6/11.
//

#ifndef DEFENCE_GAME_MONSTERLINKLISTMANAGER_H
#define DEFENCE_GAME_MONSTERLINKLISTMANAGER_H


class MonsterLinkListManager {

};


#endif //DEFENCE_GAME_MONSTERLINKLISTMANAGER_H
